package by.overpas.detekt.intellij.kotlin.styleissues

import dev.detekt.api.RuleSet
import dev.detekt.api.RuleSetId
import dev.detekt.api.RuleSetProvider

class StyleIssuesRuleSetProvider : RuleSetProvider {

    override val ruleSetId = RuleSetId("intellij-kotlin-style-issues")

    override fun instance() =
        RuleSet(
            ruleSetId,
            listOf(
                ::AddOperatorModifier,
                ::AddVarianceModifier,
                ::BooleanLiteralArgument,
                ::CascadeIf,
                ::CollectionConcatenationToBuildCollection,
                ::ConvertPairConstructorToToFunction,
                ::ConvertRangeCheckToTwoComparisons,
                ::ConvertReferenceToLambda,
                ::ConvertSealedClassToSealedInterface,
                ::ConvertSealedInterfaceToSealedClass,
                ::ConvertSecondaryConstructorToPrimary,
                ::ConvertToExplicitBackingFields,
                ::ConvertToStringTemplate,
                ::ConvertTryFinallyToUseCall,
                ::ConvertTwoComparisonsToRangeCheck,
                ::CopyWithoutNamedArguments,
                ::DestructuringDeclaration,
                ::FilterIsInstanceCallWithClassLiteralArgument,
                ::FoldInitializerAndIfToElvis,
                ::IfThenToElvis,
                ::IfThenToSafeAccess,
                ::ImplicitThis,
                ::IntroduceWhenSubject,
                ::JavaMapForEach,
                ::JoinDeclarationAndAssignment,
                ::LiftReturnOrAssignment,
                ::MapToForEach,
                ::MoveLambdaOutsideParentheses,
                ::MoveVariableDeclarationIntoWhen,
                ::NullableHashCode,
                ::RedundantAsSequence,
                ::RedundantElseInIf,
                ::RedundantObjectTypeCheck,
                ::RedundantRunCatching,
                ::RemoveEmptyParenthesesFromAnnotationEntry,
                ::ReplaceAddAllWithMapTo,
                ::ReplaceAssertBooleanWithAssertEquality,
                ::ReplaceAssociateFunction,
                ::ReplaceCallWithBinaryOperator,
                ::ReplaceCollectionCountWithSize,
                ::ReplaceContains,
                ::ReplaceIfExpressionWithFirstOrNull,
                ::ReplaceJavaStaticMethodWithKotlinAnalog,
                ::ReplaceManualRangeWithIndicesCalls,
                ::ReplaceMapGetOrDefault,
                ::ReplaceMapIndexedWithListGenerator,
                ::ReplaceMapKeysCallChainWithKeys,
                ::ReplaceNegatedIsEmptyWithIsNotEmpty,
                ::ReplaceNotNullAssertionWithElvisReturn,
                ::ReplaceRangeStartEndInclusiveWithFirstLast,
                ::ReplaceReadLineWithReadln,
                ::ReplaceSizeCheckWithIsNotEmpty,
                ::ReplaceSizeZeroCheckWithIsEmpty,
                ::ReplaceStringFormatWithLiteral,
                ::ReplaceSubstringWithDropLast,
                ::ReplaceSubstringWithIndexingOperation,
                ::ReplaceSubstringWithSubstringAfter,
                ::ReplaceSubstringWithSubstringBefore,
                ::ReplaceSubstringWithTake,
                ::ReplaceToStringWithStringTemplate,
                ::ReplaceToWithInfixForm,
                ::ReplaceUntilWithRangeUntil,
                ::ReplaceWithCallWithContextCall,
                ::ReplaceWithIgnoreCaseEquals,
                ::ReplaceWithImportAlias,
                ::ReplaceWithOperatorAssignment,
                ::RevertExplicitBackingFields,
                ::SafeCastWithReturn,
                ::SimplifiableCall,
                ::SimplifiableCallChain,
                ::SimplifyAssertNotNull,
                ::SimplifyBooleanWithConstants,
                ::SimplifyNegatedBinaryExpression,
                ::SimplifyNestedEachInScopeFunction,
                ::UnclearPrecedenceOfBinaryExpression,
                ::UnlabeledReturnInsideLambda,
                ::UnsafeCastWithReturn,
                ::UseExpressionBody,
                ::UsePropertyAccessSyntax,
                ::VerboseNullabilityAndEmptiness,
            ),
        )
}
